modificado el readme y autoinstall de depend
ffpp2003/SAPEIClient pull request #21
Opened 2024-10-28 19:36 UTC by gaston1709

2024-11-04 01:50 UTC, ffpp2003 approved these changes

2024-11-04 14:07 UTC, Corte0 requested changes
Agregar explicacion de como actualizar el submodulo

2024-11-17 15:10 UTC, ffpp2003 approved these changes

2024-11-18 16:43 UTC, ffpp2003 approved these changes

2024-11-19 02:23 UTC, Corte0 approved these changes

2024-11-19 02:25 UTC, merged